name: AutoService SB construcao e teste

on:
  push:
    branches:
      - "main"
jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - name: baixar o codigo
        uses: actions/checkout@v4
      - name: configurando o java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'oracle'
      - name: executar maven
        run: mvn clean install -DskipTests
      - name: gerando docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{secrets.REPO_NAME}} .
      - name: login dockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p '${{ secrets.DOCKER_PASS }}'
      - name: publicar a image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{secrets.REPO_NAME}}

  instalacao_aws:
    runs-on: self-hosted
    needs: construir
    steps:
      - name: pegar imagem
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{secrets.REPO_NAME}}
      - name: baixar o dockercompose
        uses: actions/checkout@v4
      - name: gerar arquivo de env
        run: |
          cat > .env << 'EOF'
          BD_URL=${{secrets.BD_URL}}
          BD_USERNAME=${{secrets.BD_USERNAME}}
          BD_PASSWORD=${{secrets.BD_PASSWORD}}
          POSTGRES_USER=${{secrets.PG_USER}}
          POSTGRES_PASSWORD=${{secrets.PG_PASS}}
          POSTGRES_DB=${{secrets.PG_BD}}
          DOCKER_IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{secrets.REPO_NAME}}
          EOF
      - name: executar container
        run: sudo docker compose up -d --remove-orphans